### ISSUE TITLE
No versions to install?

### ISSUE THREAD

**Issue by Reached** [ryayoung/python-solver#1]
Thanks for providing this.

When I try to install I get this error:

Tried `pip3 install excel_solver` and `pip3 install excel-solver`

```
ERROR: Could not find a version that satisfies the requirement excel_solver (from versions: none)
ERROR: No matching distribution found for excel_solver
```

Any ideas?

**Comment by ryayoung** [comment]
It's likely you need a newer python version. It's listed as requiring >=3.10 on pypi, but I think it would work with 3.9 if you fork/clone and update the version in the pyproject.toml
